### ISSUE TITLE
nopCommerce 4.20 Upgrade

### ISSUE THREAD

**Issue by DennisVerhoevenDC** [nopWay/HasProducts-discount-requiremement-plugin-for-nopcommerce#1]
Hello there,

I was wondering if this plugin was still being maintained, since it has been out of date since nopCommerce 4.20 was released.

Thanks for your answer :)

**Comment by onuradsay** [comment]
Hi, now you can download [latest release](https://github.com/nopWay/HasProducts-discount-requiremement-plugin-for-nopcommerce/releases/latest) which supports nopCommerce 4.20

I thought that nobody is using this plugin :) If anything goes wrong with the new release, please let me know.
